# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Maven
trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: execute_tests
  displayName: 'Run Browserstack'
  steps:
    - script: |
        echo "Setting up environment variables"
        echo "##vso[task.setvariable variable=SOME_KEY]$(SOME_KEY)"
        echo "Printing secret token"
        echo $(SOME_KEY)
      displayName: 'Setup Environment Variables'
      env:
        SECRET_TOKEN: $(secretKey)

    - task: BrowserStackConfig@0
      inputs:
        BrowserStackServiceEndPoint: 'BrowserStackConnection'
        browserstackLocal: true

    - task: BrowserStackConfig@0
      inputs:
        BrowserStackServiceEndPoint: 'BrowserStackConnection'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'JDKVersion'
        options: '-DskipTests'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        mavenVersionOption: Default
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        goals: 'clean install'

    - script: |
        echo "Running Selenide TestNG tests"
        mvn test -Dsurefire.suiteXmlFiles=$(System.DefaultWorkingDirectory)/testng.xml
      displayName: 'Run Selenide TestNG Tests'
      continueOnError: true

    - task: BrowserStackResults@1
      inputs:
        browserstackProduct: 'automate'