# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Maven
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'BrowserStackConnection'
    browserstackLocal: true

- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'BrowserStackConnection'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    echo "Running Selenide TestNG tests"
    mvn test -Dsurefire.suiteXmlFiles=$(System.DefaultWorkingDirectory)/testng.xml
  displayName: 'Run Selenide TestNG Tests'
  continueOnError: true

- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'